#!/bin/bash

BINDIR=$(realpath $(dirname $(realpath $0))/../cli)

rm -rf /var/tmp/test-xmltojson-*
TESTDIR=/var/tmp/test-xmltojson-$$
mkdir -p $TESTDIR/samples $TESTDIR/gold $TESTDIR/output

cp samples/*.xml.xz samples/*.xml $TESTDIR/samples/
unxz $TESTDIR/samples/*.xml.xz

cp gold/*.json.xz gold/*.json $TESTDIR/gold/
unxz $TESTDIR/gold/*.json.xz

$(ls -1Ht *.tar.xz *.tar.bz2 2> /dev/null | sed -E s/\.tar\..+//)

cd $TESTDIR/samples
for i in $(ls -1 *.xml 2> /dev/null | sed -E s/\.xml// ) ; do
    echo "checking against $i.xml..."
    $BINDIR/xmltojson $i.xml $TESTDIR/output/
    diff -c $TESTDIR/gold/$i.json $TESTDIR/output/$i.json > $TESTDIR/output/$i.diff
    if [ -s $TESTDIR/output/$i.diff ]; then
        echo "... $i.xml checked FAILED!"
    fi
done
