#!/usr/bin/python

import sys, os
from satools.sysstat import fetch_fileheader, fetch_os_code, Invalid

if os.path.getsize(sys.argv[1]) == 0:
    print >> sys.stderr, "Invalid - %s: empty data file" % sys.argv[1]
    sys.exit(1)

try:
    fm, fh, fa, magic = fetch_fileheader(sys.argv[1])
except Invalid as e:
    print >> sys.stderr, "Invalid - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
except Exception as e:
    print >> sys.stderr, "Error - %s: %s" % (sys.argv[1], e)
    sys.exit(1)

try:
    val = fetch_os_code(magic)
except Invalid as e:
    print >> sys.stderr, "Invalid - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
except Exception as e:
    print >> sys.stderr, "Error - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
else:
    print val
