#!/usr/bin/python

import sys, os
from satools.sysstat import verify_contents, Invalid, Corruption, Truncated

if len(sys.argv) < 2:
    print >> sys.stderr, "Missing sa data file name to verify"
    sys.exit(1)

if os.path.getsize(sys.argv[1]) == 0:
    print >> sys.stderr, "Invalid - %s: empty data file" % sys.argv[1]
    sys.exit(1)

if len(sys.argv) > 2:
    tgt_hostname = sys.argv[2]
else:
    tgt_hostname = None

try:
    verify_contents(sys.argv[1], tgt_hostname)
except Invalid as e:
    print >> sys.stderr, "Invalid - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
except Corruption as e:
    print >> sys.stderr, "Corrupted - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
except Truncated as e:
    print >> sys.stderr, "Truncated - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
except Exception as e:
    print >> sys.stderr, "Error - %s: %s" % (sys.argv[1], e)
    sys.exit(1)
